# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Fb6aGBMNGtDLQzHfec1j4FTMcZ-cuOS
"""

!pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('groceries.csv', header = None)
dataset=dataset.drop(columns=[0])
dataset=dataset.drop(dataset.index[0])
transactions = []
for i in range(1, 9835):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 32)])

from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

res = list(rules)

res

def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
DF = pd.DataFrame(inspect(results), columns = ['Item1', 'Item2', 'Support', 'Confidence', 'Lift'])
DF.style.set_caption('Offers available for the items in a grocery store using Apriori (Associate Rule Learning)')

DF
DF.style.set_caption('Offers available for the items in a grocery store using Apriori (Associate Rule Learning)')

DF.nlargest( n=9835,columns = 'Lift')
DF.style.set_caption('Offers available for the items in a grocery store using Apriori (Associate Rule Learning)')